name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.9.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install

  biome:
    runs-on: ubuntu-22.04
    needs: setup
    steps:
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci ./src

  typescript:
    runs-on: ubuntu-22.04
    needs: setup
    steps:
      - name: Run TypeScript Compiler
        run: pnpm tsc

  prisma:
    runs-on: ubuntu-22.04
    needs: setup
    steps:
      - name: Generate Prisma Client
        run: pnpm prisma generate

  build:
    runs-on: ubuntu-22.04
    needs: [setup, biome, typescript, prisma]
    steps:
      - name: Build Project
        run: pnpm run build
